project:
  type: website

website:
  title: "First Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - sidebar:sources
      - sidebar:interactive
        
  sidebar:
    - id: sources
      title: "Sources"
      style: "floating"
      background: "#ffffff"
      collapse-level: 2
      contents: 
        - source-1.qmd
        - source-2.qmd
        
    - id: interactive
      title: "Interactive Pages"
      style: "floating"
      background: "#ffffff"
      collapse-level: 2
      contents: 
        - plane-passengers.qmd
        - maps.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



